services:
  postgres-db:
    image: postgres:16-alpine # Sử dụng bản Postgres nhẹ và ổn định
    container_name: nest-postgres-container
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '${POSTGRES_PORT}:5432' # Mở cổng 5432 từ container ra máy thật (localhost)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Giữ lại dữ liệu kể cả khi tắt container

volumes:
  postgres_data:
